quarkus.http.port=8080

# DataSource ? PostgreSQL (ver local/docker-compose.yml)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=ada.tech
quarkus.datasource.password=turma1660
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/bancada

# Hibernate ORM
quarkus.hibernate-orm.log.sql=true

# Force o banco a usar UTC para todos os tipos de data e hora
# quarkus.hibernate-orm.jdbc.timezone=UTC

# ---------------------------------------------------------------
# JWT ? Segurança
# ---------------------------------------------------------------
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=meeting-room-api
smallrye.jwt.sign.key.location=privateKey.pem
